name = "BTDevcraft 4.3"
author = "BT"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84f86e9940727a88044f6352fd33dee2c47cc2b380529426557bad6e6bd7c2ff"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
