name = "BTDevcraft 4.3"
author = "BT"
version = "4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c00fffda2044b4c0327cec132057b9155fac87cd5d59f79d58f38b5a47a8d2c"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.2"]
