name = "BTDevcraft 3.1"
author = "BT"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66674d8e0306fdc0fcd066670ab70b1433bfd96e96dc3f3dc33f6fe890209945"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
