name = "BTDevcraft 4.0"
author = "BT"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf6d78e663de3cd4972d42569efdf4d9b44307437e10bd6322b5868a34e44e34"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9", "1.21.10"]
