name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    name: Create Release and Upload ZIP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up release variables
        id: vars
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          mkdir release
          cd multimc
          zip -r ../release/btdevcraft.zip instance.cfg mmc-pack.json server-icon.png .minecraft/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          files: release/btdevcraft.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
