name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: btdevcraft
          # Path to the file to upload
          path: |
            multimc/instance.cfg
            multimc/mmc-pack.json
            multimc/server-icon.png
            multimc/.minecraft/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "btdevcraft"
